### ISSUE TITLE
no _dump_data is defined for class Thread::Mutex

### ISSUE THREAD

**Issue by jcoyne** [samvera/active_fedora#1378]
```
     Failure/Error: marshalled = Marshal.dump(post)
     
     TypeError:
       no _dump_data is defined for class Thread::Mutex
     # ./spec/integration/marshal_spec.rb:23:in `dump'
     # ./spec/integration/marshal_spec.rb:23:in `block (3 levels) in <top (required)>'
```

This started occuring several months ago. Is it possible this is correlated with ActiveTriples 1.1.0?

**Comment by jcoyne** [comment]
Rdf 3.0.6 was released in that timeframe and added a Mutex: https://github.com/ruby-rdf/rdf/releases/tag/3.0.6

**Comment by cjcolvar** [comment]
I reverted to `rdf` 3.0.5 and the failing tests passed.  I think we should pin to `rdf` 3.0.5 for now and fix this in `rdf` by implementing `marshal_dump` and `marshal_load`.  I'm working on a PR to `rdf` now.
