### ISSUE TITLE
BelongsToAssociation writer/reader bug (AF 6.7.6)

### ISSUE THREAD

**Issue by dchandekstark** [samvera/active_fedora#346]
Example:

`TestModel` is related to `AdminPolicy`:

``` ruby
belongs_to :admin_policy, :property => :is_governed_by
```

However:

```
> obj2.admin_policy = obj1.admin_policy
> obj2.save!
```

throws an exception:

```
2.0.0-p247 :001 > obj1 = FactoryGirl.create(:test_model)
 => #<TestModel pid:"changeme:8", contributor:[], coverage:[], creator:[], date:[], description:[], identifier:["test00001"], language:[], publisher:[], relation:[], rights:[], source:[], subject:[], title:["DulHydra Test Object"], type:[], license_title:"", license_description:"", license_url:"", descmetadata_source:nil> 
2.0.0-p247 :002 > apo1 = FactoryGirl.create(:admin_policy)
 => #<AdminPolicy pid:"changeme:9", title:"Admin Policy", description:nil, license_title:"", license_description:"", license_url:"", default_license_title:"", default_license_description:"", default_license_url:""> 
2.0.0-p247 :003 > obj2 = FactoryGirl.create(:test_model)
 => #<TestModel pid:"changeme:10", contributor:[], coverage:[], creator:[], date:[], description:[], identifier:["test00002"], language:[], publisher:[], relation:[], rights:[], source:[], subject:[], title:["DulHydra Test Object"], type:[], license_title:"", license_description:"", license_url:"", descmetadata_source:nil> 
2.0.0-p247 :006 > obj1.admin_policy = apo1
 => #<AdminPolicy pid:"changeme:9", title:"Admin Policy", description:nil, license_title:"", license_description:"", license_url:"", default_license_title:"", default_license_description:"", default_license_url:""> 
2.0.0-p247 :007 > obj1.save!
 => true 
2.0.0-p247 :008 > obj2.admin_policy = obj1.admin_policy
 => #<AdminPolicy pid:"changeme:9", title:"Admin Policy", description:nil, license_title:"", license_description:"", license_url:"", default_license_title:"", default_license_description:"", default_license_url:""> 
2.0.0-p247 :009 > obj2.save!
ArgumentError: Invalid target "#<AdminPolicy:0x007fe901f728c0>". Target must be specified as a literal, or be a valid URI.
    from /Users/dc/.rvm/gems/ruby-2.0.0-p247@develop/gems/active-fedora-6.7.6/lib/active_fedora/relationship_graph.rb:89:in `rescue in build_statement'
    from /Users/dc/.rvm/gems/ruby-2.0.0-p247@develop/gems/active-fedora-6.7.6/lib/active_fedora/relationship_graph.rb:80:in `build_statement'
    from /Users/dc/.rvm/gems/ruby-2.0.0-p247@develop/gems/active-fedora-6.7.6/lib/active_fedora/relationship_graph.rb:62:in `block (2 levels) in to_graph'
    from /Users/dc/.rvm/gems/ruby-2.0.0-p247@develop/gems/active-fedora-6.7.6/lib/active_fedora/relationship_graph.rb:61:in `each'
    from /Users/dc/.rvm/gems/ruby-2.0.0-p247@develop/gems/active-fedora-6.7.6/lib/active_fedora/relationship_graph.rb:61:in `block in to_graph'
    from /Users/dc/.rvm/gems/ruby-2.0.0-p247@develop/gems/active-fedora-6.7.6/lib/active_fedora/relationship_graph.rb:60:in `each'
    from /Users/dc/.rvm/gems/ruby-2.0.0-p247@develop/gems/active-fedora-6.7.6/lib/active_fedora/relationship_graph.rb:60:in `to_graph'
    from /Users/dc/.rvm/gems/ruby-2.0.0-p247@develop/gems/active-fedora-6.7.6/lib/active_fedora/semantic_node.rb:111:in `relationships'
    from /Users/dc/.rvm/gems/ruby-2.0.0-p247@develop/gems/active-fedora-6.7.6/lib/active_fedora/rels_ext_datastream.rb:40:in `relationships'
    from /Users/dc/.rvm/gems/ruby-2.0.0-p247@develop/gems/active-fedora-6.7.6/lib/active_fedora/rels_ext_datastream.rb:69:in `block in to_rels_ext'
    from /Users/dc/.rvm/gems/ruby-2.0.0-p247@develop/gems/rdf-1.1.1.1/lib/rdf/writer.rb:152:in `call'
    from /Users/dc/.rvm/gems/ruby-2.0.0-p247@develop/gems/rdf-1.1.1.1/lib/rdf/writer.rb:152:in `block (2 levels) in buffer'
    from /Users/dc/.rvm/gems/ruby-2.0.0-p247@develop/gems/rdf-rdfxml-1.0.1/lib/rdf/rdfxml/writer.rb:93:in `call'
    from /Users/dc/.rvm/gems/ruby-2.0.0-p247@develop/gems/rdf-rdfxml-1.0.1/lib/rdf/rdfxml/writer.rb:93:in `block in initialize'
    from /Users/dc/.rvm/gems/ruby-2.0.0-p247@develop/gems/rdf-1.1.1.1/lib/rdf/writer.rb:221:in `instance_eval'
    from /Users/dc/.rvm/gems/ruby-2.0.0-p247@develop/gems/rdf-1.1.1.1/lib/rdf/writer.rb:221:in `initialize'
... 12 levels...
    from /Users/dc/.rvm/gems/ruby-2.0.0-p247@develop/gems/active-fedora-6.7.6/lib/active_fedora/callbacks.rb:238:in `persist'
    from /Users/dc/.rvm/gems/ruby-2.0.0-p247@develop/gems/active-fedora-6.7.6/lib/active_fedora/persistence.rb:145:in `update_record'
    from /Users/dc/.rvm/gems/ruby-2.0.0-p247@develop/gems/active-fedora-6.7.6/lib/active_fedora/callbacks.rb:246:in `block in update_record'
    from /Users/dc/.rvm/gems/ruby-2.0.0-p247@develop/gems/activesupport-4.0.2/lib/active_support/callbacks.rb:373:in `_run__812416328190789249__update__callbacks'
    from /Users/dc/.rvm/gems/ruby-2.0.0-p247@develop/gems/activesupport-4.0.2/lib/active_support/callbacks.rb:80:in `run_callbacks'
    from /Users/dc/.rvm/gems/ruby-2.0.0-p247@develop/gems/active-fedora-6.7.6/lib/active_fedora/callbacks.rb:246:in `update_record'
    from /Users/dc/.rvm/gems/ruby-2.0.0-p247@develop/gems/active-fedora-6.7.6/lib/active_fedora/persistence.rb:14:in `save'
    from /Users/dc/.rvm/gems/ruby-2.0.0-p247@develop/gems/active-fedora-6.7.6/lib/active_fedora/validations.rb:50:in `save'
    from /Users/dc/.rvm/gems/ruby-2.0.0-p247@develop/gems/active-fedora-6.7.6/lib/active_fedora/persistence.rb:21:in `save!'
    from /Users/dc/.rvm/gems/ruby-2.0.0-p247@develop/gems/active-fedora-6.7.6/lib/active_fedora/validations.rb:56:in `save!'
    from (irb):9
    from /Users/dc/.rvm/gems/ruby-2.0.0-p247@develop/gems/railties-4.0.2/lib/rails/commands/console.rb:90:in `start'
    from /Users/dc/.rvm/gems/ruby-2.0.0-p247@develop/gems/railties-4.0.2/lib/rails/commands/console.rb:9:in `start'
    from /Users/dc/.rvm/gems/ruby-2.0.0-p247@develop/gems/railties-4.0.2/lib/rails/commands.rb:62:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

**Comment by jrgriffiniii** [comment]
Closing due to this being resolved (please see https://github.com/samvera/active_fedora/issues/346#issuecomment-33978121)
